### ISSUE TITLE
Invite users by twitter tag to discussions

### ISSUE THREAD

**Issue by tim-harper** [delphis-inc/delphisbe#35]
This will require 1 query and 1 mutation:

* Query:
  * The query should take in a string and query for twitter users using the Twitter API. The Twitter API will return a list of Users. We should make sure to use the requesting user's Twitter OAuth tokens.
  * The query should then, for each user that is returned, check whether that user already has an account in Chatham and if so check to see if they have an invite for this discussion *created by the inviting user*. NOTE: this should be optimized into a single SQL query if possible.
  * The response should be an object that has a field for the `twitterUserInfo` and a boolean for `invited`. Invited should be set to true if and only if I have invited this user to this discussion already.

* Mutation:
  * The inviting user can invite these twitter users to the discussion. Let's build this mutation to invite multiple users at once because we will do this in the future.
  * The mutation should respond with a list of discussion invite objects based on which invites were created

**Comment by nedrocks** [comment]
I have updated the contents of this issue to be more accurate in the current implementation requirements.

**Comment by jasondellaluce** [comment]
Perfect!
